### ISSUE TITLE
В базе данных не хватает индексов

### ISSUE THREAD

**Issue by bovops** [u236/homed-service-recorder#1]
Перенес свою базу рекордера на шлюз от МТС, пошли тормоза:
`homed-recorder[5450]: 2024.08.10 21:00:17.535 (inf) recorder:  Hour data stored in 17517 ms`
![telegram-cloud-photo-size-2-5314328078505335725-y](https://github.com/user-attachments/assets/a18c222e-d056-4b82-8e1d-c0e249294297)

В таблице data у меня накопилось 490к записей.
Добавил индекс в базу:
`CREATE INDEX idx_item_id_timestamp ON data(item_id, timestamp)`

**Comment by u236** [comment]
мы с кем-то уже экспериментировали с индексами и это как раз и вызывало тормоза, без индексов база работала быстрее, подозреваю, что проц в МТС-шлюзе просто слабоват для такого количества данных, нужно больше экспериментов, я пока не готов добавить индексы, есть вероятность, что это может негативно повлиять на БД других пользователей

**Comment by u236** [comment]
провел только что эксперимент, у меня в БД порядка 40к записей, сделал копию БД и добавил индексы, средняя скорость выборки для суточного графика выросла с 25-30 до 40-45 мс, так что увы, но я ничего не буду менять, пока не появится другая статистика

**Comment by bovops** [comment]
Вол логи со шлюза МТС:
`Mon Aug 12 10:00:01 2024 daemon.info homed-recorder[2379]: 2024.08.12 10:00:01.482 (inf) recorder:  Hour data stored in 620 ms`

Без индекса это занимало 17517 ms

**Comment by u236** [comment]
> Без индекса это занимало 17517 ms

Я не сомневаюсь, что это так, когда в базе пол миллиона записей, но еще раз повторю - когда в базе пол сотни тысяч записей, добавление индексов вызывает замедление выборки в полтора раза. Я абсолютно уверен, что в истории homed-recorder есть всего одна база, в которой пол миллиона записей и ты, судя по всему, вполне справился с ручным добавлением индексов, так что я не вижу причин портить из за всего этого жизнь остальным пользователям. Если будут повторные случаи, нужно будет определить некий предел количества записей, при котором индексы начинают работать на ускорение и добавить их автоматическое добавление, а пока пусть все остается как есть.
